### ISSUE TITLE
SSH tunnel with ed25519 private key

### ISSUE THREAD

**Issue by zapicoj** [ThePicklenat0r/hassio-addons#19]
Hello,
I am using SSH Tunneling Client addon  to establish a tunnel between HA OS and an external Linux server. I can do a ssh connection manually using Teminal & SSH addon, just including the key file in the .ssh folder and doing the cli "ssh user@serverip -p myport". I would like to use the same key file with SSH Tunneling Client but I don't see where I have to locate the file, or how to set it, in the config file. 
Could you give me some tip in order to use SSH Tunneling Client with asymetrical keys authentication ?
I am running HA OS in a RPi-4 with RPi-Debian Bookworm 64bits
Appreciate any comment
Jose Zapico

**Comment by dy1io** [comment]
I think I understand what you're trying to do.. You essentially want to supply the add-on with the private key to use for the connection, is that correct?

If that is the case, the add-on does not support supplying the key. In theory that isn't a very difficult thing to add, and if I have some time I may look into finding a way to do that, or feel free to submit a PR if you have a solution you'd like to suggest. My original thought on that and why I originally didn't go that way was that I wanted to ensure I was always using a unique key for best security practice, so it was easier for me to just generate the key and display the public key.

If you want to use it that way just head over to the log and copy the public key (and hash if you need it) into your server's `authorized_keys` and it should connect just like it does from your CLI.

**Comment by zapicoj** [comment]
Thank you for your response and time.
Yes, your understanding is correct.  The reason is because  the server, that I am using to establish the ssh connection, does not support rsa keys for ssh connections, it accepts ed25519, ECDSA, EdDSA and others. 
This is why I wanted to configured the SSH Tunnel with my own ed25519 private key file. 
I understand and agree on your point about best security practice. May be a good option (keeping your concept), would be to select the key type in the config file. But in that case the SSH Tunnel should have different key generators (depending on the type) and that sounds a bit complex.
The obvious option would be allow the user to provide the private key file in the configuration file. But in that case we dont respect your idea of using a unique key for best security practice.
In the meanwhile I will try to find another server allowing the use of RSA keys for ssh connections in order to use your excelent add-ons.
Appreciate much your time

kind regards
Jose Zapico

**Comment by zapicoj** [comment]
Hi,
After talking with the system administrator, he agreed to open the option of RSA key for ssh connections. 
Now the SSH Tunnel addon can connect with the server but it does not make the port forwarding. I receive those lines in the addon register, after connection:
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

I will continue trying to find out why those lines appear in the log.

Thank you
Jose Zapico
