### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by aasimenator** [ThePicklenat0r/hassio-addons#2]
Hi, I am sure I am doing something incorrectly.

I added your add-on and updated the following in the configuration section before starting the addon.

![image](https://user-images.githubusercontent.com/49643079/137263976-e7073b70-a9ae-4a9b-ad21-0aa8556d1e31.png)

The logs look fine
![image](https://user-images.githubusercontent.com/49643079/137264030-3178abae-d35b-48be-9166-3a67220f4b39.png)

Yet when i try to browse the url from the status page of ngrok client I get 400: Bad Request
![image](https://user-images.githubusercontent.com/49643079/137264102-195b947d-175b-4dd5-812a-1332289cfd7f.png)

Any ideas?

**Comment by ThamzaDev** [comment]
Hello, I was wondering if this was solved ?

**Comment by dy1io** [comment]
> Hello, I was wondering if this was solved ?

This issue is caused by not adding the trusted proxies to your configuration.yaml as outlined in step 4 on the docs page. Also note that the ngrok addon is no longer supported and I don't plan to release any updates for it.
